version: '3'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-dev-web
    ports:
      - "3001:3001"
    volumes:
      - .:/app-dev-web
      - /app-dev-web/node_modules
